name: Validate Genesis and collect gentxs
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: |
          wget https://github.com/cosmic-horizon/coho/releases/download/v0.1/cohod-v0.1-linux-amd64
          chmod +x cohod-v0.1-linux-amd64
          sudo mv cohod-v0.1-linux-amd64 /bin/coho
          coho init test
          mkdir $HOME/.coho/config/gentx
          cp ./genesis.json $HOME/.coho/config/
          cp ./gentxs/* $HOME/.coho/config/gentx/
      - name: Validate Genesis
        run: coho validate-genesis
      - name: Collect Gentxs
        run: coho collect-gentxs